name: Test
on:
  workflow_dispatch
    
jobs:
  create-docs-build:
    name: Windows release build
    runs-on: windows-latest
    steps:
      - name: Checkout the core source code
      - uses: actions/checkout@master
        with:
          name: ManiVaultStudio/core
      - name: Setup oxygen
      - uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: 'submodule/'
          doxyfile-path: 'docs/Doxygen'
